### PR TITLE
Created the Tutorial

### LINKED ISSUE #19: Write intro for first time user
First time users should be greeted by a main explanation screen.

### PR DESCRIPTION
**Pull request by torch2424**
Created a nice little tutorial closes #19 

Also allowed for easy access to the tutorial

this also finished #8 

As it completes the skeleton for all of the functionality of the app.

Lastly this cleaned up alot of the css visually, and things aren't looking terrible

### CODE REVIEW

**Comment by julianpoy** [comment]
This looks great!

There are a few things though.
screenshot from 2016-02-27 22-19-51
See how the text is... absolutely giant? We need to figure out why thats so big. I notice it is small on your screen, yet very very large on both Alexis' and my computer screens.

The homepage "Need some help? Click me!"... Could that be a button like the "Open Folder" button on the left sidebar? I think it would look cleaner (think Slack type appearance)

**Comment by julianpoy** [comment]
And I realize now when I post that screenshot it does not encompass how EXTREMELY large that text is. Im talking 

# HUGE

(and ^ thats still not even half as big as how it shows up on my screen hahaha)

**Comment by torch2424** [comment]
Oh yeah I can fix that

**Comment by torch2424** [comment]
Can I pull in then fix while I'm fixing your icons?

**Comment by julianpoy** [comment]
Shweit

**Comment by julianpoy** [comment]
Yeah that's cool. Im going to tackle some other JS based things

**Comment by torch2424** [comment]
also, I do agree it's big (I realize my elementary screen always shrunk stuff for me), but I would like somethings on the larger side, since when your performing at night, it usually helps to have a little bit larger text, especially if your using your laptop while standing

**Pull request merged**
